name: example
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  fast_develop:
    path: ../

  # Toast插件 https://pub.flutter-io.cn/packages/oktoast
  oktoast: ^3.2.0

  #  https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.5.3+2

  # State https://pub.flutter-io.cn/packages/provider
  provider: ^6.0.3

  fast_mvvm: ^2.1.3

  fast_router: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

